title: PenTestAlpha
email: info@pentestaplha.com
description: >- # this means to ignore newlines until "baseurl:"
  Website and blog on pentesting, and getting into security.
baseurl: ""
url: "https://pentestalpha.com"

paginate: 5
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
sass:
  sass_dir: _sass
