title: PenTestAlpha
email: info@pentestaplha.com
description: >- # this means to ignore newlines until "baseurl:"
  Website and blog on pentesting, and getting into security.
baseurl: ""
url: "https://pentestalpha.com"

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
